# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36f327f497d5f512678745b8f96701e11f8f6829d8cce8446bcb629ad0eb9785675d3ed122d37609e21d75a9327e178b0788e24bb0c8227ebd346f307d078820

test:
  secret_key_base: 8cac82dd26b8dda7aac896058053edabf8da4c6c3eb9b03b7a7576b261fb33c5cdce67db9f1f46a3e53d4a1cc04064e8c6f8308f55e44dbd8b0848c18cc43992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
